name: Java CI

on:
  pull_request:
    branches: [main, master]

jobs:
  quality-gate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile Java
        run: ./gradlew compileJava

      - name: Run tests
        run: ./gradlew test

      - name: Check code formatting
        run: make format

      - name: Run linting and code quality checks
        run: ./gradlew lint

      - name: Run SpotBugs analysis
        run: ./gradlew spotbugsMain

      - name: Run full validation
        run: ./gradlew preCommit
